---
- hosts: webserver
  remote_user: name
  become: yes
  become_method: su 
  tasks:
    - name: template modifying
      template:
        src: template.j2
        dst: /etc/conf/example.conf
      
      notify:
        - restart memcached
        - restart apache
